### ISSUE TITLE
don't return result

### ISSUE THREAD

**Issue by ArrowZQ** [mher/tornado-celery#56]
Don't return result if worker of celery execute a long time.how can i fix this issue.

handler:
```
@asynchronous
@gen.coroutine
def get(self):
    response = yield gen.Task(test_a.apply_async, task_id='1111')
    self.write(str(response.result))
    self.finish()

```

if the task is:
```
@app.task(name='test_a')
def test_a():
    return "hello !!!"
```
everthing is ok, the result will return correct. the celery logs is 
[2015-10-11 17:51:26,238: INFO/MainProcess] Received task: test_a[1111]
[2015-10-11 17:51:26,240: INFO/MainProcess] Task test_a[1111] succeeded in 0.00181979499757s: 'hello !!!'

but if the task is:
```
@app.task(name='test_a')
def test_a():
    i = 0
    while i < 10000000:
        i = i + 1
    return "hello !!!"
```
the result will not return. the celery logs is 
[2015-10-11 17:50:39,348: INFO/MainProcess] Received task: test_a[1111]
[2015-10-11 17:50:39,896: INFO/MainProcess] Task test_a[1111] succeeded in 0.54682576601s: 'hello !!!'

**Comment by zhkzyth** [comment]
@ArrowZQ 

a long runing task might get blocked  cos tcelery will add a timeout logic in tornado ioloop.And such a timeout logic will remove the bussiness callback if a task doesn't response for so long.Although tcelery remove the callback, but it doesn't disconnect the request, which i think is a bug~

You may should try to increase the timeout, or just decrease the task execution time.

**Comment by ArrowZQ** [comment]
OK, thx.
